### ISSUE TITLE
Replace Fantom Logo with fantom_wallet_logo logos

### ISSUE THREAD

**Issue by MKong** [Fantom-foundation/fantom-mobile-app#58]
![fantom_wallet_logo_w](https://user-images.githubusercontent.com/5106444/49922041-d1312600-fef2-11e8-84ab-7e5bce32b789.png)
![fantom_wallet_logo_b](https://user-images.githubusercontent.com/5106444/49922043-d1c9bc80-fef2-11e8-89b6-79da967a002d.png)

**Comment by Kapilbindal1** [comment]
Done
