### ISSUE TITLE
Clicking on unstake shows a dialog in the background which does not let me do anything

### ISSUE THREAD

**Issue by faridnsh** [Fantom-foundation/fantom-mobile-app#81]
You can see the problem in the picture:

![image](https://user-images.githubusercontent.com/822510/72294116-33f47400-3655-11ea-86fa-10ef5695a1bd.png)
 
This is on my Galaxy S8 running Android 9.

**Comment by MKong** [comment]
Should be fixed on latest Android and iOS builds.
